//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientePagos.PagosServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deuda", Namespace="http://usfx.edu.bo/pagos")]
    [System.SerializableAttribute()]
    public partial class Deuda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConceptoField;
        
        private decimal MontoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Concepto {
            get {
                return this.ConceptoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConceptoField, value) != true)) {
                    this.ConceptoField = value;
                    this.RaisePropertyChanged("Concepto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://usfx.edu.bo/pagos", ConfigurationName="PagosServiceRef.PagosServiceSoap")]
    public interface PagosServiceSoap {
        
        // CODEGEN: Generating message contract since element name ci from namespace http://usfx.edu.bo/pagos is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://usfx.edu.bo/pagos/verDeuda", ReplyAction="*")]
        ClientePagos.PagosServiceRef.verDeudaResponse verDeuda(ClientePagos.PagosServiceRef.verDeudaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usfx.edu.bo/pagos/verDeuda", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientePagos.PagosServiceRef.verDeudaResponse> verDeudaAsync(ClientePagos.PagosServiceRef.verDeudaRequest request);
        
        // CODEGEN: Generating message contract since element name ci from namespace http://usfx.edu.bo/pagos is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://usfx.edu.bo/pagos/registrarPago", ReplyAction="*")]
        ClientePagos.PagosServiceRef.registrarPagoResponse registrarPago(ClientePagos.PagosServiceRef.registrarPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usfx.edu.bo/pagos/registrarPago", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientePagos.PagosServiceRef.registrarPagoResponse> registrarPagoAsync(ClientePagos.PagosServiceRef.registrarPagoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verDeudaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verDeuda", Namespace="http://usfx.edu.bo/pagos", Order=0)]
        public ClientePagos.PagosServiceRef.verDeudaRequestBody Body;
        
        public verDeudaRequest() {
        }
        
        public verDeudaRequest(ClientePagos.PagosServiceRef.verDeudaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://usfx.edu.bo/pagos")]
    public partial class verDeudaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string primerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombres;
        
        public verDeudaRequestBody() {
        }
        
        public verDeudaRequestBody(string ci, string primerApellido, string nombres) {
            this.ci = ci;
            this.primerApellido = primerApellido;
            this.nombres = nombres;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verDeudaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verDeudaResponse", Namespace="http://usfx.edu.bo/pagos", Order=0)]
        public ClientePagos.PagosServiceRef.verDeudaResponseBody Body;
        
        public verDeudaResponse() {
        }
        
        public verDeudaResponse(ClientePagos.PagosServiceRef.verDeudaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://usfx.edu.bo/pagos")]
    public partial class verDeudaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientePagos.PagosServiceRef.Deuda[] verDeudaResult;
        
        public verDeudaResponseBody() {
        }
        
        public verDeudaResponseBody(ClientePagos.PagosServiceRef.Deuda[] verDeudaResult) {
            this.verDeudaResult = verDeudaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarPago", Namespace="http://usfx.edu.bo/pagos", Order=0)]
        public ClientePagos.PagosServiceRef.registrarPagoRequestBody Body;
        
        public registrarPagoRequest() {
        }
        
        public registrarPagoRequest(ClientePagos.PagosServiceRef.registrarPagoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://usfx.edu.bo/pagos")]
    public partial class registrarPagoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int deudaId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ci;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string empresa;
        
        public registrarPagoRequestBody() {
        }
        
        public registrarPagoRequestBody(int deudaId, string ci, string empresa) {
            this.deudaId = deudaId;
            this.ci = ci;
            this.empresa = empresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarPagoResponse", Namespace="http://usfx.edu.bo/pagos", Order=0)]
        public ClientePagos.PagosServiceRef.registrarPagoResponseBody Body;
        
        public registrarPagoResponse() {
        }
        
        public registrarPagoResponse(ClientePagos.PagosServiceRef.registrarPagoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://usfx.edu.bo/pagos")]
    public partial class registrarPagoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool registrarPagoResult;
        
        public registrarPagoResponseBody() {
        }
        
        public registrarPagoResponseBody(bool registrarPagoResult) {
            this.registrarPagoResult = registrarPagoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PagosServiceSoapChannel : ClientePagos.PagosServiceRef.PagosServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagosServiceSoapClient : System.ServiceModel.ClientBase<ClientePagos.PagosServiceRef.PagosServiceSoap>, ClientePagos.PagosServiceRef.PagosServiceSoap {
        
        public PagosServiceSoapClient() {
        }
        
        public PagosServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PagosServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagosServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagosServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientePagos.PagosServiceRef.verDeudaResponse ClientePagos.PagosServiceRef.PagosServiceSoap.verDeuda(ClientePagos.PagosServiceRef.verDeudaRequest request) {
            return base.Channel.verDeuda(request);
        }
        
        public ClientePagos.PagosServiceRef.Deuda[] verDeuda(string ci, string primerApellido, string nombres) {
            ClientePagos.PagosServiceRef.verDeudaRequest inValue = new ClientePagos.PagosServiceRef.verDeudaRequest();
            inValue.Body = new ClientePagos.PagosServiceRef.verDeudaRequestBody();
            inValue.Body.ci = ci;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.nombres = nombres;
            ClientePagos.PagosServiceRef.verDeudaResponse retVal = ((ClientePagos.PagosServiceRef.PagosServiceSoap)(this)).verDeuda(inValue);
            return retVal.Body.verDeudaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientePagos.PagosServiceRef.verDeudaResponse> ClientePagos.PagosServiceRef.PagosServiceSoap.verDeudaAsync(ClientePagos.PagosServiceRef.verDeudaRequest request) {
            return base.Channel.verDeudaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientePagos.PagosServiceRef.verDeudaResponse> verDeudaAsync(string ci, string primerApellido, string nombres) {
            ClientePagos.PagosServiceRef.verDeudaRequest inValue = new ClientePagos.PagosServiceRef.verDeudaRequest();
            inValue.Body = new ClientePagos.PagosServiceRef.verDeudaRequestBody();
            inValue.Body.ci = ci;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.nombres = nombres;
            return ((ClientePagos.PagosServiceRef.PagosServiceSoap)(this)).verDeudaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientePagos.PagosServiceRef.registrarPagoResponse ClientePagos.PagosServiceRef.PagosServiceSoap.registrarPago(ClientePagos.PagosServiceRef.registrarPagoRequest request) {
            return base.Channel.registrarPago(request);
        }
        
        public bool registrarPago(int deudaId, string ci, string empresa) {
            ClientePagos.PagosServiceRef.registrarPagoRequest inValue = new ClientePagos.PagosServiceRef.registrarPagoRequest();
            inValue.Body = new ClientePagos.PagosServiceRef.registrarPagoRequestBody();
            inValue.Body.deudaId = deudaId;
            inValue.Body.ci = ci;
            inValue.Body.empresa = empresa;
            ClientePagos.PagosServiceRef.registrarPagoResponse retVal = ((ClientePagos.PagosServiceRef.PagosServiceSoap)(this)).registrarPago(inValue);
            return retVal.Body.registrarPagoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientePagos.PagosServiceRef.registrarPagoResponse> ClientePagos.PagosServiceRef.PagosServiceSoap.registrarPagoAsync(ClientePagos.PagosServiceRef.registrarPagoRequest request) {
            return base.Channel.registrarPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientePagos.PagosServiceRef.registrarPagoResponse> registrarPagoAsync(int deudaId, string ci, string empresa) {
            ClientePagos.PagosServiceRef.registrarPagoRequest inValue = new ClientePagos.PagosServiceRef.registrarPagoRequest();
            inValue.Body = new ClientePagos.PagosServiceRef.registrarPagoRequestBody();
            inValue.Body.deudaId = deudaId;
            inValue.Body.ci = ci;
            inValue.Body.empresa = empresa;
            return ((ClientePagos.PagosServiceRef.PagosServiceSoap)(this)).registrarPagoAsync(inValue);
        }
    }
}
